### PR TITLE
Add support for open door event

### PR DESCRIPTION
**Pull request by riemers**
Fixes https://github.com/basschipper/homeassistant-doorbird-proxy/issues/1

### CODE REVIEW

**Comment by basschipper** [comment]
Thanx!

**Comment by riemers** [comment]
Don't forget to update the docker hub (https://hub.docker.com/r/basschipper/homeassistant-doorbird-proxy/tags/) 👍

**Comment by basschipper** [comment]
Mmmm, thought that the image would build automatically on push. Triggered it manually, thanx!

**Comment by riemers** [comment]
Seems someone made a component, doesn't have what you have 'yet' https://home-assistant.io/components/doorbird/

**Pull request merged**
